import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/header";
import Footer from "./_components/Footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3300"),
  title: {
    template: "%s | シンプルなコーポレートサイト",
    default: "シンプルなコーポレートサイト"
  },
  description: "「Next.js+ヘッドレスCMSではじめる! 簡単・モダンWebサイト制作入門」で作成されるサイトです",
  openGraph: {
    title: "シンプルなコーポレートサイト",
    description: "「Next.js+ヘッドレスCMSではじめる! 簡単・モダンWebサイト制作入門」で作成されるサイトです",
    images: ["/ogp.png"],
  },
  alternates: {
    canonical: "http://localhost:3300",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
